### ISSUE TITLE
Rna seq cgl fails on zcat

### ISSUE THREAD

**Issue by JakeNarkizian** [BD2KGenomics/toil-scripts#362]
## Command:
```
(toil-scripts) ubuntu@ip-172-31-18-211:/mnt/ephemeral$ toil-rnaseq run /mnt/ephemeral/jobStore/ --retryCount=1 --workDir=/mnt/ephemeral/data --manifest=manifest-toil-rnaseq.tsv
```
## log:
```
ip-172-31-18-211: 2016-07-16 20:53:50,490 INFO: toil.lib.bioio: Logging set at level: INFO
ip-172-31-18-211: 2016-07-16 20:53:50,490 INFO: toil.lib.bioio: Logging set at level: INFO
ip-172-31-18-211: 2016-07-16 20:53:50,492 INFO: toil.jobStores.fileJobStore: Path to job store directory is '/mnt/ephemeral/jobStore'.
ip-172-31-18-211: 2016-07-16 20:53:50,492 INFO: toil.jobStores.abstractJobStore: The workflow ID is: 'c07d8b52-d778-4d67-806e-8bb00ad3fd1b'
ip-172-31-18-211: 2016-07-16 20:53:50,494 INFO: toil.common: Using the single machine batch system
ip-172-31-18-211: 2016-07-16 20:53:50,494 WARNING: toil.batchSystems.singleMachine: Limiting maxCores to CPU count of system (32).
ip-172-31-18-211: 2016-07-16 20:53:50,494 WARNING: toil.batchSystems.singleMachine: Limiting maxMemory to physically available memory (63321128960).
ip-172-31-18-211: 2016-07-16 20:53:50,495 INFO: toil.batchSystems.singleMachine: Setting up the thread pool with 320 workers, given a minimum CPU fraction of 0.100000 and a maximum CPU value of 32.
ip-172-31-18-211: 2016-07-16 20:53:50,554 INFO: toil.common: Written the environment for the jobs to the environment file
ip-172-31-18-211: 2016-07-16 20:53:50,554 INFO: toil.common: Caching all jobs in job store
ip-172-31-18-211: 2016-07-16 20:53:50,554 INFO: toil.common: 0 jobs downloaded.
ip-172-31-18-211: 2016-07-16 20:53:50,556 INFO: toil.realtimeLogger: Real-time logging disabled
ip-172-31-18-211: 2016-07-16 20:53:50,558 INFO: toil.leader: (Re)building internal scheduler state
ip-172-31-18-211: 2016-07-16 20:53:50,558 INFO: toil.leader: Checked batch system has no running jobs and no updated jobs
ip-172-31-18-211: 2016-07-16 20:53:50,558 INFO: toil.leader: Found 1 jobs to start and 0 jobs with successors to run
ip-172-31-18-211: 2016-07-16 20:53:50,562 INFO: toil.leader: Starting the main loop
ip-172-31-18-211: 2016-07-16 20:53:50,563 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/jobStore/ W/B/jobkFyHQF'.
INFO:toil.common:Created the workflow directory at /mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b
ip-172-31-18-211: 2016-07-16 20:53:50,829 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/jobStore/ U/u/jobgHpjt1'.
ip-172-31-18-211: 2016-07-16 20:53:51,090 INFO: toil.leader: Got message from job at time 07-16-2016 20:53:51: UUID: 6f4a6944-9437-4549-b574-342261291192
URL: https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/wcdt/oicr_issue42_input/RNA150410JA_10_1-1-15_M12_EV_05uM_JQ1.tar
Paired: False
File Type: tar
Cores: 32
CIMode: None
ip-172-31-18-211: 2016-07-16 20:54:36,401 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/jobStore/ B/Y/jobWFLX8h'.
ip-172-31-18-211: 2016-07-16 20:54:36,662 INFO: toil.leader: Got message from job at time 07-16-2016 20:54:36: Successfully deleted local copies of file with ID 'i/Z/tmpHbv9VK.tmp'.
ip-172-31-18-211: 2016-07-16 20:54:37,621 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/jobStore/ 3/Y/jobFzyxf1'.
ip-172-31-18-211: 2016-07-16 20:54:37,664 INFO: toil.leader: Got message from job at time 07-16-2016 20:54:37: Processing sample tar and queueing CutAdapt for: 6f4a6944-9437-4549-b574-342261291192
ip-172-31-18-211: 2016-07-16 20:54:37,664 INFO: toil.leader: Got message from job at time 07-16-2016 20:54:37: Added file with ID 'N/y/tmpLFdOph.tmp' to the list of files to be globally deleted.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 1215, in asyncWrite
    raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 1215, in asyncWrite
    raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting


ip-172-31-18-211: 2016-07-16 20:56:09,148 WARNING: toil.leader: The jobWrapper seems to have left a log file, indicating failure: 3/Y/jobFzyxf1
ip-172-31-18-211: 2016-07-16 20:56:09,148 WARNING: toil.leader: Reporting file: 3/Y/jobFzyxf1
ip-172-31-18-211: 2016-07-16 20:56:09,149 WARNING: toil.leader: 3/Y/jobFzyxf1:	---TOIL WORKER OUTPUT LOG---
ip-172-31-18-211: 2016-07-16 20:56:09,149 WARNING: toil.leader: 3/Y/jobFzyxf1:	WARNING:toil.resource:The localize() method should only be invoked on a worker.
ip-172-31-18-211: 2016-07-16 20:56:09,149 WARNING: toil.leader: 3/Y/jobFzyxf1:	WARNING:toil.resource:Can't find resource for leader path '/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts'
ip-172-31-18-211: 2016-07-16 20:56:09,149 WARNING: toil.leader: 3/Y/jobFzyxf1:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages', name='toil_scripts.rnaseq_cgl.rnaseq_cgl_pipeline')
ip-172-31-18-211: 2016-07-16 20:56:09,149 WARNING: toil.leader: 3/Y/jobFzyxf1:	WARNING:toil.resource:The localize() method should only be invoked on a worker.
ip-172-31-18-211: 2016-07-16 20:56:09,149 WARNING: toil.leader: 3/Y/jobFzyxf1:	WARNING:toil.resource:Can't find resource for leader path '/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts'
ip-172-31-18-211: 2016-07-16 20:56:09,149 WARNING: toil.leader: 3/Y/jobFzyxf1:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages', name='toil_scripts.rnaseq_cgl.rnaseq_cgl_pipeline')
ip-172-31-18-211: 2016-07-16 20:56:09,149 WARNING: toil.leader: 3/Y/jobFzyxf1:	INFO:toil.fileStore:LOG-TO-MASTER: Processing sample: 6f4a6944-9437-4549-b574-342261291192
ip-172-31-18-211: 2016-07-16 20:56:09,149 WARNING: toil.leader: 3/Y/jobFzyxf1:	INFO:toil.fileStore:CACHE: Cache hit on file with ID 'i/Z/tmpHbv9VK.tmp'.
ip-172-31-18-211: 2016-07-16 20:56:09,149 WARNING: toil.leader: 3/Y/jobFzyxf1:	
ip-172-31-18-211: 2016-07-16 20:56:09,149 WARNING: toil.leader: 3/Y/jobFzyxf1:	gzip: /mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmptnBjD7/7da9859d-36fe-46e6-bf37-df96a4a356dd/tnkzQIB/sample.tar: not in gzip format
ip-172-31-18-211: 2016-07-16 20:56:09,149 WARNING: toil.leader: 3/Y/jobFzyxf1:	INFO:toil.fileStore:LOG-TO-MASTER: Successfully deleted local copies of file with ID 'i/Z/tmpHbv9VK.tmp'.
ip-172-31-18-211: 2016-07-16 20:56:09,149 WARNING: toil.leader: 3/Y/jobFzyxf1:	Traceback (most recent call last):
ip-172-31-18-211: 2016-07-16 20:56:09,149 WARNING: toil.leader: 3/Y/jobFzyxf1:	  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 330, in main
ip-172-31-18-211: 2016-07-16 20:56:09,150 WARNING: toil.leader: 3/Y/jobFzyxf1:	    job._runner(jobWrapper=jobWrapper, jobStore=jobStore, fileStore=fileStore)
ip-172-31-18-211: 2016-07-16 20:56:09,150 WARNING: toil.leader: 3/Y/jobFzyxf1:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1043, in _runner
ip-172-31-18-211: 2016-07-16 20:56:09,150 WARNING: toil.leader: 3/Y/jobFzyxf1:	    returnValues = self._run(jobWrapper, fileStore)
ip-172-31-18-211: 2016-07-16 20:56:09,150 WARNING: toil.leader: 3/Y/jobFzyxf1:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 991, in _run
ip-172-31-18-211: 2016-07-16 20:56:09,150 WARNING: toil.leader: 3/Y/jobFzyxf1:	    return self.run(fileStore)
ip-172-31-18-211: 2016-07-16 20:56:09,150 WARNING: toil.leader: 3/Y/jobFzyxf1:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1136, in run
ip-172-31-18-211: 2016-07-16 20:56:09,150 WARNING: toil.leader: 3/Y/jobFzyxf1:	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
ip-172-31-18-211: 2016-07-16 20:56:09,150 WARNING: toil.leader: 3/Y/jobFzyxf1:	  File "/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts/rnaseq_cgl/rnaseq_cgl_pipeline.py", line 215, in process_sample_tar
ip-172-31-18-211: 2016-07-16 20:56:09,150 WARNING: toil.leader: 3/Y/jobFzyxf1:	    subprocess.check_call([command] + fastqs, stdout=f)
ip-172-31-18-211: 2016-07-16 20:56:09,150 WARNING: toil.leader: 3/Y/jobFzyxf1:	  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
ip-172-31-18-211: 2016-07-16 20:56:09,150 WARNING: toil.leader: 3/Y/jobFzyxf1:	    raise CalledProcessError(retcode, cmd)
ip-172-31-18-211: 2016-07-16 20:56:09,150 WARNING: toil.leader: 3/Y/jobFzyxf1:	CalledProcessError: Command '['zcat', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmptnBjD7/7da9859d-36fe-46e6-bf37-df96a4a356dd/tnkzQIB/RNA150410JA_10_1-1-15_M12_EV_05uM_JQ1_GAGCTGAA_L003_R1_007.fastq.gz', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmptnBjD7/7da9859d-36fe-46e6-bf37-df96a4a356dd/tnkzQIB/sample.tar', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmptnBjD7/7da9859d-36fe-46e6-bf37-df96a4a356dd/tnkzQIB/RNA150410JA_10_1-1-15_M12_EV_05uM_JQ1_GAGCTGAA_L003_R1_005.fastq.gz', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmptnBjD7/7da9859d-36fe-46e6-bf37-df96a4a356dd/tnkzQIB/RNA150410JA_10_1-1-15_M12_EV_05uM_JQ1_GAGCTGAA_L003_R1_006.fastq.gz', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmptnBjD7/7da9859d-36fe-46e6-bf37-df96a4a356dd/tnkzQIB/RNA150410JA_10_1-1-15_M12_EV_05uM_JQ1_GAGCTGAA_L003_R1_003.fastq.gz', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmptnBjD7/7da9859d-36fe-46e6-bf37-df96a4a356dd/tnkzQIB/RNA150410JA_10_1-1-15_M12_EV_05uM_JQ1_GAGCTGAA_L003_R1_009.fastq.gz', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmptnBjD7/7da9859d-36fe-46e6-bf37-df96a4a356dd/tnkzQIB/RNA150410JA_10_1-1-15_M12_EV_05uM_JQ1_GAGCTGAA_L003_R1_004.fastq.gz', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmptnBjD7/7da9859d-36fe-46e6-bf37-df96a4a356dd/tnkzQIB/RNA150410JA_10_1-1-15_M12_EV_05uM_JQ1_GAGCTGAA_L003_R1_002.fastq.gz', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmptnBjD7/7da9859d-36fe-46e6-bf37-df96a4a356dd/tnkzQIB/RNA150410JA_10_1-1-15_M12_EV_05uM_JQ1_GAGCTGAA_L003_R1_008.fastq.gz', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmptnBjD7/7da9859d-36fe-46e6-bf37-df96a4a356dd/tnkzQIB/RNA150410JA_10_1-1-15_M12_EV_05uM_JQ1_GAGCTGAA_L003_R1_001.fastq.gz']' returned non-zero exit status 1
ip-172-31-18-211: 2016-07-16 20:56:09,150 WARNING: toil.leader: 3/Y/jobFzyxf1:	Exiting the worker because of a failed jobWrapper on host ip-172-31-18-211
ip-172-31-18-211: 2016-07-16 20:56:09,150 WARNING: toil.leader: 3/Y/jobFzyxf1:	ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-18-211
ip-172-31-18-211: 2016-07-16 20:56:09,150 WARNING: toil.leader: 3/Y/jobFzyxf1:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job 3/Y/jobFzyxf1 to 1
ip-172-31-18-211: 2016-07-16 20:56:09,151 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/jobStore/ 3/Y/jobFzyxf1'.
^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A                                Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 1215, in asyncWrite
    raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 1215, in asyncWrite
    raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting


ip-172-31-18-211: 2016-07-16 20:57:41,031 WARNING: toil.leader: The jobWrapper seems to have left a log file, indicating failure: 3/Y/jobFzyxf1
ip-172-31-18-211: 2016-07-16 20:57:41,031 WARNING: toil.leader: Reporting file: 3/Y/jobFzyxf1
ip-172-31-18-211: 2016-07-16 20:57:41,032 WARNING: toil.leader: 3/Y/jobFzyxf1:	---TOIL WORKER OUTPUT LOG---
ip-172-31-18-211: 2016-07-16 20:57:41,032 WARNING: toil.leader: 3/Y/jobFzyxf1:	WARNING:toil.resource:The localize() method should only be invoked on a worker.
ip-172-31-18-211: 2016-07-16 20:57:41,032 WARNING: toil.leader: 3/Y/jobFzyxf1:	WARNING:toil.resource:Can't find resource for leader path '/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts'
ip-172-31-18-211: 2016-07-16 20:57:41,032 WARNING: toil.leader: 3/Y/jobFzyxf1:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages', name='toil_scripts.rnaseq_cgl.rnaseq_cgl_pipeline')
ip-172-31-18-211: 2016-07-16 20:57:41,032 WARNING: toil.leader: 3/Y/jobFzyxf1:	WARNING:toil.resource:The localize() method should only be invoked on a worker.
ip-172-31-18-211: 2016-07-16 20:57:41,032 WARNING: toil.leader: 3/Y/jobFzyxf1:	WARNING:toil.resource:Can't find resource for leader path '/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts'
ip-172-31-18-211: 2016-07-16 20:57:41,032 WARNING: toil.leader: 3/Y/jobFzyxf1:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages', name='toil_scripts.rnaseq_cgl.rnaseq_cgl_pipeline')
ip-172-31-18-211: 2016-07-16 20:57:41,032 WARNING: toil.leader: 3/Y/jobFzyxf1:	INFO:toil.fileStore:LOG-TO-MASTER: Processing sample: 6f4a6944-9437-4549-b574-342261291192
ip-172-31-18-211: 2016-07-16 20:57:41,032 WARNING: toil.leader: 3/Y/jobFzyxf1:	INFO:toil.fileStore:CACHE: Cache hit on file with ID 'i/Z/tmpHbv9VK.tmp'.
ip-172-31-18-211: 2016-07-16 20:57:41,032 WARNING: toil.leader: 3/Y/jobFzyxf1:	
ip-172-31-18-211: 2016-07-16 20:57:41,032 WARNING: toil.leader: 3/Y/jobFzyxf1:	gzip: /mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmpIAvfLM/25753d0d-2eb1-427e-bd38-31dadab73db1/twGEsO6/sample.tar: not in gzip format
ip-172-31-18-211: 2016-07-16 20:57:41,032 WARNING: toil.leader: 3/Y/jobFzyxf1:	INFO:toil.fileStore:LOG-TO-MASTER: Successfully deleted local copies of file with ID 'i/Z/tmpHbv9VK.tmp'.
ip-172-31-18-211: 2016-07-16 20:57:41,032 WARNING: toil.leader: 3/Y/jobFzyxf1:	Traceback (most recent call last):
ip-172-31-18-211: 2016-07-16 20:57:41,032 WARNING: toil.leader: 3/Y/jobFzyxf1:	  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 330, in main
ip-172-31-18-211: 2016-07-16 20:57:41,032 WARNING: toil.leader: 3/Y/jobFzyxf1:	    job._runner(jobWrapper=jobWrapper, jobStore=jobStore, fileStore=fileStore)
ip-172-31-18-211: 2016-07-16 20:57:41,033 WARNING: toil.leader: 3/Y/jobFzyxf1:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1043, in _runner
ip-172-31-18-211: 2016-07-16 20:57:41,033 WARNING: toil.leader: 3/Y/jobFzyxf1:	    returnValues = self._run(jobWrapper, fileStore)
ip-172-31-18-211: 2016-07-16 20:57:41,033 WARNING: toil.leader: 3/Y/jobFzyxf1:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 991, in _run
ip-172-31-18-211: 2016-07-16 20:57:41,033 WARNING: toil.leader: 3/Y/jobFzyxf1:	    return self.run(fileStore)
ip-172-31-18-211: 2016-07-16 20:57:41,033 WARNING: toil.leader: 3/Y/jobFzyxf1:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1136, in run
ip-172-31-18-211: 2016-07-16 20:57:41,033 WARNING: toil.leader: 3/Y/jobFzyxf1:	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
ip-172-31-18-211: 2016-07-16 20:57:41,033 WARNING: toil.leader: 3/Y/jobFzyxf1:	  File "/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts/rnaseq_cgl/rnaseq_cgl_pipeline.py", line 215, in process_sample_tar
ip-172-31-18-211: 2016-07-16 20:57:41,033 WARNING: toil.leader: 3/Y/jobFzyxf1:	    subprocess.check_call([command] + fastqs, stdout=f)
ip-172-31-18-211: 2016-07-16 20:57:41,033 WARNING: toil.leader: 3/Y/jobFzyxf1:	  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
ip-172-31-18-211: 2016-07-16 20:57:41,033 WARNING: toil.leader: 3/Y/jobFzyxf1:	    raise CalledProcessError(retcode, cmd)
ip-172-31-18-211: 2016-07-16 20:57:41,033 WARNING: toil.leader: 3/Y/jobFzyxf1:	CalledProcessError: Command '['zcat', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmpIAvfLM/25753d0d-2eb1-427e-bd38-31dadab73db1/twGEsO6/RNA150410JA_10_1-1-15_M12_EV_05uM_JQ1_GAGCTGAA_L003_R1_007.fastq.gz', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmpIAvfLM/25753d0d-2eb1-427e-bd38-31dadab73db1/twGEsO6/sample.tar', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmpIAvfLM/25753d0d-2eb1-427e-bd38-31dadab73db1/twGEsO6/RNA150410JA_10_1-1-15_M12_EV_05uM_JQ1_GAGCTGAA_L003_R1_005.fastq.gz', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmpIAvfLM/25753d0d-2eb1-427e-bd38-31dadab73db1/twGEsO6/RNA150410JA_10_1-1-15_M12_EV_05uM_JQ1_GAGCTGAA_L003_R1_006.fastq.gz', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmpIAvfLM/25753d0d-2eb1-427e-bd38-31dadab73db1/twGEsO6/RNA150410JA_10_1-1-15_M12_EV_05uM_JQ1_GAGCTGAA_L003_R1_003.fastq.gz', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmpIAvfLM/25753d0d-2eb1-427e-bd38-31dadab73db1/twGEsO6/RNA150410JA_10_1-1-15_M12_EV_05uM_JQ1_GAGCTGAA_L003_R1_009.fastq.gz', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmpIAvfLM/25753d0d-2eb1-427e-bd38-31dadab73db1/twGEsO6/RNA150410JA_10_1-1-15_M12_EV_05uM_JQ1_GAGCTGAA_L003_R1_004.fastq.gz', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmpIAvfLM/25753d0d-2eb1-427e-bd38-31dadab73db1/twGEsO6/RNA150410JA_10_1-1-15_M12_EV_05uM_JQ1_GAGCTGAA_L003_R1_002.fastq.gz', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmpIAvfLM/25753d0d-2eb1-427e-bd38-31dadab73db1/twGEsO6/RNA150410JA_10_1-1-15_M12_EV_05uM_JQ1_GAGCTGAA_L003_R1_008.fastq.gz', '/mnt/ephemeral/data/toil-c07d8b52-d778-4d67-806e-8bb00ad3fd1b/tmpIAvfLM/25753d0d-2eb1-427e-bd38-31dadab73db1/twGEsO6/RNA150410JA_10_1-1-15_M12_EV_05uM_JQ1_GAGCTGAA_L003_R1_001.fastq.gz']' returned non-zero exit status 1
ip-172-31-18-211: 2016-07-16 20:57:41,033 WARNING: toil.leader: 3/Y/jobFzyxf1:	Exiting the worker because of a failed jobWrapper on host ip-172-31-18-211
ip-172-31-18-211: 2016-07-16 20:57:41,033 WARNING: toil.leader: 3/Y/jobFzyxf1:	ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-18-211
ip-172-31-18-211: 2016-07-16 20:57:41,033 WARNING: toil.leader: 3/Y/jobFzyxf1:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job 3/Y/jobFzyxf1 to 0
ip-172-31-18-211: 2016-07-16 20:57:41,034 WARNING: toil.leader: Job: 3/Y/jobFzyxf1 is completely failed
ip-172-31-18-211: 2016-07-16 20:57:45,034 INFO: toil.leader: No jobs left to run so exiting.
ip-172-31-18-211: 2016-07-16 20:57:45,034 INFO: toil.leader: Finished the main loop
ip-172-31-18-211: 2016-07-16 20:57:45,034 INFO: toil.leader: Waiting for stats and logging collator process to finish ...
ip-172-31-18-211: 2016-07-16 20:57:45,500 INFO: toil.leader: ... finished collating stats and logs. Took 0.465316057205 seconds
ip-172-31-18-211: 2016-07-16 20:57:45,500 INFO: toil.leader: Waiting for service manager thread to finish ...
ip-172-31-18-211: 2016-07-16 20:57:45,595 INFO: toil.leader: ... finished shutting down the service manager. Took 0.0953528881073 seconds
ip-172-31-18-211: 2016-07-16 20:57:45,596 INFO: toil.leader: Finished toil run with 3 failed jobs
ip-172-31-18-211: 2016-07-16 20:57:45,596 INFO: toil.leader: Failed jobs at end of the run: set(['B/Y/jobWFLX8h', 'W/B/jobkFyHQF', '3/Y/jobFzyxf1'])
Traceback (most recent call last):
  File "/home/ubuntu/toil-scripts/bin/toil-rnaseq", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts/rnaseq_cgl/rnaseq_cgl_pipeline.py", line 505, in main
    Job.Runner.startToil(Job.wrapJobFn(map_job, download_sample, samples, config), args)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 500, in startToil
    return toil.start(job)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 561, in start
    return self._runMainLoop(job)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 775, in _runMainLoop
    jobCache=self._jobCache)
  File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 694, in mainLoop
    raise FailedJobsException( config.jobStore, len(toilState.totalFailedJobs) )
toil.leader.FailedJobsException: The job store '/mnt/ephemeral/jobStore/' contains 3 failed jobs
```

**Comment by jvivian** [comment]
@JakeNarkizian — Can I see the contents of the **manifest-toil-rnaseq.tsv**? It looks like it's trying to zcat the fastqgz and the tar together which it shouldn't be doing... this may be an artifact of removing the `os.remove` of the sample tar to be compatible with caching.

**Comment by jvivian** [comment]
Yup, this is a `glob` issue due to removing `os.remove`. I will address this in a **2.0.1** hotfix.

**Comment by jvivian** [comment]
@JakeNarkizian — Please assign bugs related to the pipeline to me when you create them so I don't miss any. Thanks!
