### ISSUE TITLE
Type error in alignment pipeline

### ISSUE THREAD

**Issue by JakeNarkizian** [BD2KGenomics/toil-scripts#363]
## Command:
```
$ toil-bwa run ./jobstore --retryCount=1 --workDir=./data --manifest=./manifest-toil-bwa.tsv
```
## log:
```
ip-172-31-18-211: 2016-07-16 21:13:43,342 INFO: toil.lib.bioio: Logging set at level: INFO
ip-172-31-18-211: 2016-07-16 21:13:43,342 INFO: toil.lib.bioio: Logging set at level: INFO
ip-172-31-18-211: 2016-07-16 21:13:43,344 INFO: toil.jobStores.fileJobStore: Path to job store directory is '/mnt/ephemeral/alignment/jobstore'.
ip-172-31-18-211: 2016-07-16 21:13:43,344 INFO: toil.jobStores.abstractJobStore: The workflow ID is: 'b8a9dff8-7537-475f-9590-484865540e97'
ip-172-31-18-211: 2016-07-16 21:13:43,346 INFO: toil.common: Using the single machine batch system
ip-172-31-18-211: 2016-07-16 21:13:43,346 WARNING: toil.batchSystems.singleMachine: Limiting maxCores to CPU count of system (32).
ip-172-31-18-211: 2016-07-16 21:13:43,347 WARNING: toil.batchSystems.singleMachine: Limiting maxMemory to physically available memory (63321128960).
ip-172-31-18-211: 2016-07-16 21:13:43,347 INFO: toil.batchSystems.singleMachine: Setting up the thread pool with 320 workers, given a minimum CPU fraction of 0.100000 and a maximum CPU value of 32.
ip-172-31-18-211: 2016-07-16 21:13:43,406 INFO: toil.common: Written the environment for the jobs to the environment file
ip-172-31-18-211: 2016-07-16 21:13:43,406 INFO: toil.common: Caching all jobs in job store
ip-172-31-18-211: 2016-07-16 21:13:43,406 INFO: toil.common: 0 jobs downloaded.
ip-172-31-18-211: 2016-07-16 21:13:43,408 INFO: toil.realtimeLogger: Real-time logging disabled
ip-172-31-18-211: 2016-07-16 21:13:43,410 INFO: toil.leader: (Re)building internal scheduler state
ip-172-31-18-211: 2016-07-16 21:13:43,410 INFO: toil.leader: Checked batch system has no running jobs and no updated jobs
ip-172-31-18-211: 2016-07-16 21:13:43,410 INFO: toil.leader: Found 1 jobs to start and 0 jobs with successors to run
ip-172-31-18-211: 2016-07-16 21:13:43,414 INFO: toil.leader: Starting the main loop
ip-172-31-18-211: 2016-07-16 21:13:43,415 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/alignment/jobstore R/Q/jobc8dx6E'.
INFO:toil.common:Created the workflow directory at /mnt/ephemeral/alignment/data/toil-b8a9dff8-7537-475f-9590-484865540e97
ip-172-31-18-211: 2016-07-16 21:13:43,682 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/alignment/jobstore C/R/jobb1iZUr'.
ip-172-31-18-211: 2016-07-16 21:13:43,682 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/alignment/jobstore 3/x/jobe8HR9i'.
ip-172-31-18-211: 2016-07-16 21:13:43,682 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/alignment/jobstore h/X/jobejp6Ha'.
ip-172-31-18-211: 2016-07-16 21:13:43,687 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/alignment/jobstore i/6/jobizzHAq'.
ip-172-31-18-211: 2016-07-16 21:13:43,687 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/alignment/jobstore I/A/jobZj7859'.
ip-172-31-18-211: 2016-07-16 21:13:43,687 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/alignment/jobstore q/0/jobjdr1Z_'.
ip-172-31-18-211: 2016-07-16 21:13:43,688 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/alignment/jobstore g/6/jobytol5E'.
ip-172-31-18-211: 2016-07-16 21:13:44,442 INFO: toil.leader: Got message from job at time 07-16-2016 21:13:44: Successfully deleted local copies of file with ID 'J/d/tmpqMOCx2.tmp'.
ip-172-31-18-211: 2016-07-16 21:13:44,443 INFO: toil.leader: Got message from job at time 07-16-2016 21:13:44: Successfully deleted local copies of file with ID 'z/H/tmpoC1Xe3.tmp'.
ip-172-31-18-211: 2016-07-16 21:13:44,443 INFO: toil.leader: Got message from job at time 07-16-2016 21:13:44: Successfully deleted local copies of file with ID 'M/r/tmpAyyQiz.tmp'.
ip-172-31-18-211: 2016-07-16 21:14:03,484 INFO: toil.leader: Got message from job at time 07-16-2016 21:14:03: Successfully deleted local copies of file with ID 'm/A/tmpulXw8Y.tmp'.
ip-172-31-18-211: 2016-07-16 21:14:23,026 INFO: toil.leader: Got message from job at time 07-16-2016 21:14:23: Successfully deleted local copies of file with ID 'k/w/tmp9pOQXQ.tmp'.
ip-172-31-18-211: 2016-07-16 21:14:50,087 INFO: toil.leader: Got message from job at time 07-16-2016 21:14:50: Successfully deleted local copies of file with ID 'D/H/tmpUWlw9G.tmp'.
ip-172-31-18-211: 2016-07-16 21:14:50,814 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/alignment/jobstore K/z/jobSDV3OX'.
ip-172-31-18-211: 2016-07-16 21:14:51,090 INFO: toil.leader: Got message from job at time 07-16-2016 21:14:51: Successfully deleted local copies of file with ID 'k/q/tmpiWm9IX.tmp'.
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 1215, in asyncWrite
    raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 1215, in asyncWrite
    raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting


ip-172-31-18-211: 2016-07-16 21:14:53,079 WARNING: toil.leader: The jobWrapper seems to have left a log file, indicating failure: K/z/jobSDV3OX
ip-172-31-18-211: 2016-07-16 21:14:53,080 WARNING: toil.leader: Reporting file: K/z/jobSDV3OX
ip-172-31-18-211: 2016-07-16 21:14:53,080 WARNING: toil.leader: K/z/jobSDV3OX:	---TOIL WORKER OUTPUT LOG---
ip-172-31-18-211: 2016-07-16 21:14:53,080 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:The localize() method should only be invoked on a worker.
ip-172-31-18-211: 2016-07-16 21:14:53,080 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:Can't find resource for leader path '/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts'
ip-172-31-18-211: 2016-07-16 21:14:53,080 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages', name='toil_scripts.lib.jobs')
ip-172-31-18-211: 2016-07-16 21:14:53,080 WARNING: toil.leader: K/z/jobSDV3OX:	INFO:toil.jobStores.fileJobStore:Path to job store directory is '/mnt/ephemeral/alignment/jobstore'.
ip-172-31-18-211: 2016-07-16 21:14:53,080 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:The localize() method should only be invoked on a worker.
ip-172-31-18-211: 2016-07-16 21:14:53,080 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:Can't find resource for leader path '/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts'
ip-172-31-18-211: 2016-07-16 21:14:53,080 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages', name='toil_scripts.lib.jobs')
ip-172-31-18-211: 2016-07-16 21:14:53,080 WARNING: toil.leader: K/z/jobSDV3OX:	INFO:toil.fileStore:LOG-TO-MASTER: Added file with ID 'G/g/tmphxkqlC.tmp' to the list of files to be globally deleted.
ip-172-31-18-211: 2016-07-16 21:14:53,080 WARNING: toil.leader: K/z/jobSDV3OX:	INFO:toil.fileStore:LOG-TO-MASTER: Added file with ID 'z/G/tmpZZtzZr.tmp' to the list of files to be globally deleted.
ip-172-31-18-211: 2016-07-16 21:14:53,080 WARNING: toil.leader: K/z/jobSDV3OX:	INFO:toil.fileStore:LOG-TO-MASTER: Added file with ID 't/p/tmpZ_lZlR.tmp' to the list of files to be globally deleted.
ip-172-31-18-211: 2016-07-16 21:14:53,081 WARNING: toil.leader: K/z/jobSDV3OX:	INFO:toil.fileStore:LOG-TO-MASTER: Added file with ID 'l/F/tmpQN9gWW.tmp' to the list of files to be globally deleted.
ip-172-31-18-211: 2016-07-16 21:14:53,081 WARNING: toil.leader: K/z/jobSDV3OX:	INFO:toil.fileStore:LOG-TO-MASTER: Added file with ID 'O/c/tmpOk9uqu.tmp' to the list of files to be globally deleted.
ip-172-31-18-211: 2016-07-16 21:14:53,081 WARNING: toil.leader: K/z/jobSDV3OX:	INFO:toil.fileStore:LOG-TO-MASTER: Added file with ID 'e/A/tmpL1sfrY.tmp' to the list of files to be globally deleted.
ip-172-31-18-211: 2016-07-16 21:14:53,081 WARNING: toil.leader: K/z/jobSDV3OX:	INFO:toil.fileStore:LOG-TO-MASTER: Added file with ID 'I/A/tmp6JaEln.tmp' to the list of files to be globally deleted.
ip-172-31-18-211: 2016-07-16 21:14:53,081 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:The localize() method should only be invoked on a worker.
ip-172-31-18-211: 2016-07-16 21:14:53,081 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:Can't find resource for leader path '/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts'
ip-172-31-18-211: 2016-07-16 21:14:53,081 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages', name='toil_scripts.bwa_alignment.bwa_alignment')
ip-172-31-18-211: 2016-07-16 21:14:53,081 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:The localize() method should only be invoked on a worker.
ip-172-31-18-211: 2016-07-16 21:14:53,081 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:Can't find resource for leader path '/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts'
ip-172-31-18-211: 2016-07-16 21:14:53,081 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages', name='toil_scripts.bwa_alignment.bwa_alignment')
ip-172-31-18-211: 2016-07-16 21:14:53,081 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:The localize() method should only be invoked on a worker.
ip-172-31-18-211: 2016-07-16 21:14:53,081 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:Can't find resource for leader path '/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts'
ip-172-31-18-211: 2016-07-16 21:14:53,081 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages', name='toil_scripts.bwa_alignment.bwa_alignment')
ip-172-31-18-211: 2016-07-16 21:14:53,081 WARNING: toil.leader: K/z/jobSDV3OX:	INFO:toil.fileStore:LOG-TO-MASTER: Downloaded sample: e0e216bc-5d60-4dee-b90d-f1f5c9e992c4. R1 https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/ucsf-pnoc/ucsf-WXS-fastq/C021_0006_T_WES.tar
ip-172-31-18-211: 2016-07-16 21:14:53,081 WARNING: toil.leader: K/z/jobSDV3OX:	R2 https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/ucsf-pnoc/ucsf-WXS-fastq/C021_0006_C_WES.tar
ip-172-31-18-211: 2016-07-16 21:14:53,082 WARNING: toil.leader: K/z/jobSDV3OX:	Starting BWA Run
ip-172-31-18-211: 2016-07-16 21:14:53,082 WARNING: toil.leader: K/z/jobSDV3OX:	Traceback (most recent call last):
ip-172-31-18-211: 2016-07-16 21:14:53,082 WARNING: toil.leader: K/z/jobSDV3OX:	  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 330, in main
ip-172-31-18-211: 2016-07-16 21:14:53,082 WARNING: toil.leader: K/z/jobSDV3OX:	    job._runner(jobWrapper=jobWrapper, jobStore=jobStore, fileStore=fileStore)
ip-172-31-18-211: 2016-07-16 21:14:53,082 WARNING: toil.leader: K/z/jobSDV3OX:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1043, in _runner
ip-172-31-18-211: 2016-07-16 21:14:53,082 WARNING: toil.leader: K/z/jobSDV3OX:	    returnValues = self._run(jobWrapper, fileStore)
ip-172-31-18-211: 2016-07-16 21:14:53,082 WARNING: toil.leader: K/z/jobSDV3OX:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 991, in _run
ip-172-31-18-211: 2016-07-16 21:14:53,082 WARNING: toil.leader: K/z/jobSDV3OX:	    return self.run(fileStore)
ip-172-31-18-211: 2016-07-16 21:14:53,082 WARNING: toil.leader: K/z/jobSDV3OX:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1136, in run
ip-172-31-18-211: 2016-07-16 21:14:53,082 WARNING: toil.leader: K/z/jobSDV3OX:	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
ip-172-31-18-211: 2016-07-16 21:14:53,082 WARNING: toil.leader: K/z/jobSDV3OX:	  File "/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts/bwa_alignment/bwa_alignment.py", line 95, in download_sample_and_align
ip-172-31-18-211: 2016-07-16 21:14:53,082 WARNING: toil.leader: K/z/jobSDV3OX:	    bam_id.addChild(copy_file_job, name=output_name, file_id=bam_id.rv(), output_dir=inputs.output_dir)
ip-172-31-18-211: 2016-07-16 21:14:53,082 WARNING: toil.leader: K/z/jobSDV3OX:	TypeError: addChild() got an unexpected keyword argument 'name'
ip-172-31-18-211: 2016-07-16 21:14:53,082 WARNING: toil.leader: K/z/jobSDV3OX:	Exiting the worker because of a failed jobWrapper on host ip-172-31-18-211
ip-172-31-18-211: 2016-07-16 21:14:53,082 WARNING: toil.leader: K/z/jobSDV3OX:	ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-18-211
ip-172-31-18-211: 2016-07-16 21:14:53,082 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job K/z/jobSDV3OX to 1
ip-172-31-18-211: 2016-07-16 21:14:53,083 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/alignment/jobstore K/z/jobSDV3OX'.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 1215, in asyncWrite
    raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 1215, in asyncWrite
    raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting


ip-172-31-18-211: 2016-07-16 21:14:55,297 WARNING: toil.leader: The jobWrapper seems to have left a log file, indicating failure: K/z/jobSDV3OX
ip-172-31-18-211: 2016-07-16 21:14:55,298 WARNING: toil.leader: Reporting file: K/z/jobSDV3OX
ip-172-31-18-211: 2016-07-16 21:14:55,298 WARNING: toil.leader: K/z/jobSDV3OX:	---TOIL WORKER OUTPUT LOG---
ip-172-31-18-211: 2016-07-16 21:14:55,298 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:The localize() method should only be invoked on a worker.
ip-172-31-18-211: 2016-07-16 21:14:55,298 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:Can't find resource for leader path '/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts'
ip-172-31-18-211: 2016-07-16 21:14:55,298 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages', name='toil_scripts.bwa_alignment.bwa_alignment')
ip-172-31-18-211: 2016-07-16 21:14:55,298 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:The localize() method should only be invoked on a worker.
ip-172-31-18-211: 2016-07-16 21:14:55,298 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:Can't find resource for leader path '/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts'
ip-172-31-18-211: 2016-07-16 21:14:55,298 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages', name='toil_scripts.bwa_alignment.bwa_alignment')
ip-172-31-18-211: 2016-07-16 21:14:55,298 WARNING: toil.leader: K/z/jobSDV3OX:	INFO:toil.fileStore:LOG-TO-MASTER: Downloaded sample: e0e216bc-5d60-4dee-b90d-f1f5c9e992c4. R1 https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/ucsf-pnoc/ucsf-WXS-fastq/C021_0006_T_WES.tar
ip-172-31-18-211: 2016-07-16 21:14:55,298 WARNING: toil.leader: K/z/jobSDV3OX:	R2 https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/ucsf-pnoc/ucsf-WXS-fastq/C021_0006_C_WES.tar
ip-172-31-18-211: 2016-07-16 21:14:55,298 WARNING: toil.leader: K/z/jobSDV3OX:	Starting BWA Run
ip-172-31-18-211: 2016-07-16 21:14:55,298 WARNING: toil.leader: K/z/jobSDV3OX:	Traceback (most recent call last):
ip-172-31-18-211: 2016-07-16 21:14:55,299 WARNING: toil.leader: K/z/jobSDV3OX:	  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 330, in main
ip-172-31-18-211: 2016-07-16 21:14:55,299 WARNING: toil.leader: K/z/jobSDV3OX:	    job._runner(jobWrapper=jobWrapper, jobStore=jobStore, fileStore=fileStore)
ip-172-31-18-211: 2016-07-16 21:14:55,299 WARNING: toil.leader: K/z/jobSDV3OX:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1043, in _runner
ip-172-31-18-211: 2016-07-16 21:14:55,299 WARNING: toil.leader: K/z/jobSDV3OX:	    returnValues = self._run(jobWrapper, fileStore)
ip-172-31-18-211: 2016-07-16 21:14:55,299 WARNING: toil.leader: K/z/jobSDV3OX:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 991, in _run
ip-172-31-18-211: 2016-07-16 21:14:55,299 WARNING: toil.leader: K/z/jobSDV3OX:	    return self.run(fileStore)
ip-172-31-18-211: 2016-07-16 21:14:55,299 WARNING: toil.leader: K/z/jobSDV3OX:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1136, in run
ip-172-31-18-211: 2016-07-16 21:14:55,299 WARNING: toil.leader: K/z/jobSDV3OX:	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
ip-172-31-18-211: 2016-07-16 21:14:55,299 WARNING: toil.leader: K/z/jobSDV3OX:	  File "/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts/bwa_alignment/bwa_alignment.py", line 95, in download_sample_and_align
ip-172-31-18-211: 2016-07-16 21:14:55,299 WARNING: toil.leader: K/z/jobSDV3OX:	    bam_id.addChild(copy_file_job, name=output_name, file_id=bam_id.rv(), output_dir=inputs.output_dir)
ip-172-31-18-211: 2016-07-16 21:14:55,299 WARNING: toil.leader: K/z/jobSDV3OX:	TypeError: addChild() got an unexpected keyword argument 'name'
ip-172-31-18-211: 2016-07-16 21:14:55,299 WARNING: toil.leader: K/z/jobSDV3OX:	Exiting the worker because of a failed jobWrapper on host ip-172-31-18-211
ip-172-31-18-211: 2016-07-16 21:14:55,299 WARNING: toil.leader: K/z/jobSDV3OX:	ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-18-211
ip-172-31-18-211: 2016-07-16 21:14:55,299 WARNING: toil.leader: K/z/jobSDV3OX:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job K/z/jobSDV3OX to 0
ip-172-31-18-211: 2016-07-16 21:14:55,299 WARNING: toil.leader: Job: K/z/jobSDV3OX is completely failed
ip-172-31-18-211: 2016-07-16 21:14:57,300 INFO: toil.leader: No jobs left to run so exiting.
ip-172-31-18-211: 2016-07-16 21:14:57,300 INFO: toil.leader: Finished the main loop
ip-172-31-18-211: 2016-07-16 21:14:57,300 INFO: toil.leader: Waiting for stats and logging collator process to finish ...
ip-172-31-18-211: 2016-07-16 21:14:57,609 INFO: toil.leader: ... finished collating stats and logs. Took 0.308731079102 seconds
ip-172-31-18-211: 2016-07-16 21:14:57,609 INFO: toil.leader: Waiting for service manager thread to finish ...
ip-172-31-18-211: 2016-07-16 21:14:58,421 INFO: toil.leader: ... finished shutting down the service manager. Took 0.811825037003 seconds
ip-172-31-18-211: 2016-07-16 21:14:58,421 INFO: toil.leader: Finished toil run with 2 failed jobs
ip-172-31-18-211: 2016-07-16 21:14:58,421 INFO: toil.leader: Failed jobs at end of the run: set(['R/Q/jobc8dx6E', 'K/z/jobSDV3OX'])
Traceback (most recent call last):
  File "/home/ubuntu/toil-scripts/bin/toil-bwa", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts/bwa_alignment/bwa_alignment.py", line 286, in main
    Job.Runner.startToil(Job.wrapJobFn(download_reference_files, config, samples), args)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 500, in startToil
    return toil.start(job)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 561, in start
    return self._runMainLoop(job)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 775, in _runMainLoop
    jobCache=self._jobCache)
  File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 694, in mainLoop
    raise FailedJobsException( config.jobStore, len(toilState.totalFailedJobs) )
toil.leader.FailedJobsException: The job store '/mnt/ephemeral/alignment/jobstore' contains 2 failed jobs
```

**Comment by jvivian** [comment]
Thanks for catching this, stupid error on my part. I either needed to use `addChildJobFn` or wrap the function like I did the upload step.
