### ISSUE TITLE
Rna seq cgl fails with OSError

### ISSUE THREAD

**Issue by JakeNarkizian** [BD2KGenomics/toil-scripts#378]
**log**:
```
ip-172-31-22-168: 2016-07-25 00:31:54,067 INFO: toil.lib.bioio: Logging set at level: INFO
ip-172-31-22-168: 2016-07-25 00:31:54,067 INFO: toil.lib.bioio: Logging set at level: INFO
ip-172-31-22-168: 2016-07-25 00:31:54,068 INFO: toil.jobStores.fileJobStore: Path to job store directory is '/mnt/ephemeral/rna/jobstore'.
ip-172-31-22-168: 2016-07-25 00:31:54,069 INFO: toil.jobStores.abstractJobStore: The workflow ID is: 'df155b28-2c4a-4438-81fb-3ffd559777fa'
ip-172-31-22-168: 2016-07-25 00:31:54,071 INFO: toil.common: Using the single machine batch system
ip-172-31-22-168: 2016-07-25 00:31:54,071 WARNING: toil.batchSystems.singleMachine: Limiting maxCores to CPU count of system (32).
ip-172-31-22-168: 2016-07-25 00:31:54,071 WARNING: toil.batchSystems.singleMachine: Limiting maxMemory to physically available memory (63321128960).
ip-172-31-22-168: 2016-07-25 00:31:54,071 INFO: toil.batchSystems.singleMachine: Setting up the thread pool with 320 workers, given a minimum CPU fraction of 0.100000 and a maximum CPU value of 32.
ip-172-31-22-168: 2016-07-25 00:31:54,183 INFO: toil.common: Written the environment for the jobs to the environment file
ip-172-31-22-168: 2016-07-25 00:31:54,184 INFO: toil.common: Caching all jobs in job store
ip-172-31-22-168: 2016-07-25 00:31:54,184 INFO: toil.common: 0 jobs downloaded.
ip-172-31-22-168: 2016-07-25 00:31:57,210 INFO: toil.realtimeLogger: Real-time logging disabled
ip-172-31-22-168: 2016-07-25 00:31:57,211 INFO: toil.leader: (Re)building internal scheduler state
ip-172-31-22-168: 2016-07-25 00:31:57,212 INFO: toil.leader: Checked batch system has no running jobs and no updated jobs
ip-172-31-22-168: 2016-07-25 00:31:57,212 INFO: toil.leader: Found 1 jobs to start and 0 jobs with successors to run
ip-172-31-22-168: 2016-07-25 00:31:57,217 INFO: toil.leader: Starting the main loop
ip-172-31-22-168: 2016-07-25 00:31:57,218 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/rna/jobstore V/S/job_uReah'.
INFO:toil.common:Created the workflow directory at /mnt/ephemeral/rna/data/toil-df155b28-2c4a-4438-81fb-3ffd559777fa
ip-172-31-22-168: 2016-07-25 00:31:58,137 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/rna/jobstore Q/2/jobxbdl4W'.
ip-172-31-22-168: 2016-07-25 00:31:58,263 INFO: toil.leader: Got message from job at time 07-25-2016 00:31:58: UUID: haje-test
URL: s3://cgl-driver-projects-encrypted/treehouse/choc_issue40_input/AH07020812.tar
Paired: False
File Type: tar
Cores: 32
CIMode: None
ip-172-31-22-168: 2016-07-25 00:34:15,672 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/rna/jobstore U/z/job_XOUhE'.
ip-172-31-22-168: 2016-07-25 00:34:15,972 INFO: toil.leader: Got message from job at time 07-25-2016 00:34:15: Processing sample tar and queueing CutAdapt for: haje-test
ip-172-31-22-168: 2016-07-25 00:34:15,972 INFO: toil.leader: Got message from job at time 07-25-2016 00:34:15: Added file with ID 'S/0/tmpVGWTmT.tmp' to the list of files to be globally deleted.
ip-172-31-22-168: 2016-07-25 00:34:15,973 INFO: toil.leader: Got message from job at time 07-25-2016 00:34:15: Successfully deleted local copies of file with ID '0/v/tmpl6XwC6.tmp'.
ip-172-31-22-168: 2016-07-25 00:34:15,990 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/rna/jobstore l/q/job_9Ztlr'.
ip-172-31-22-168: 2016-07-25 00:40:48,668 INFO: toil.leader: Got message from job at time 07-25-2016 00:40:48: Processing sample: haje-test
ip-172-31-22-168: 2016-07-25 00:40:48,669 INFO: toil.leader: Got message from job at time 07-25-2016 00:40:48: Successfully deleted cached copy of file with ID '0/v/tmpl6XwC6.tmp'.
ip-172-31-22-168: 2016-07-25 00:40:48,669 INFO: toil.leader: Got message from job at time 07-25-2016 00:40:48: Successfully deleted local copies of file with ID '0/v/tmpl6XwC6.tmp'.
ip-172-31-22-168: 2016-07-25 00:40:48,669 INFO: toil.leader: Got message from job at time 07-25-2016 00:40:48: CACHE: Successfully removed file with ID '0/v/tmpl6XwC6.tmp'.
ip-172-31-22-168: 2016-07-25 00:40:48,669 INFO: toil.leader: Got message from job at time 07-25-2016 00:40:48: Added file with ID '0/v/tmpl6XwC6.tmp' to the list of files to be globally deleted.
ip-172-31-22-168: 2016-07-25 00:40:48,669 INFO: toil.leader: Got message from job at time 07-25-2016 00:40:48: Successfully deleted cached copy of file with ID '0/v/tmpl6XwC6.tmp'.
ip-172-31-22-168: 2016-07-25 00:40:48,669 INFO: toil.leader: Got message from job at time 07-25-2016 00:40:48: Successfully deleted local copies of file with ID '0/v/tmpl6XwC6.tmp'.
ip-172-31-22-168: 2016-07-25 00:40:48,669 INFO: toil.leader: Got message from job at time 07-25-2016 00:40:48: Added file with ID '0/v/tmpl6XwC6.tmp' to the list of files to be globally deleted.
ip-172-31-22-168: 2016-07-25 00:40:48,669 INFO: toil.leader: Got message from job at time 07-25-2016 00:40:48: Successfully deleted local copies of file with ID 't/3/tmpBM7nIk.tmp'.
ip-172-31-22-168: 2016-07-25 00:40:48,669 INFO: toil.leader: Got message from job at time 07-25-2016 00:40:48: Successfully deleted local copies of file with ID '0/v/tmpl6XwC6.tmp'.
ip-172-31-22-168: 2016-07-25 00:40:49,659 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/rna/jobstore b/8/job1TULPe'.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 1215, in asyncWrite
    raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 1215, in asyncWrite
    raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting


Exception RuntimeError: RuntimeError('cannot join current thread',) in <bound method FileStore.__del__ of <toil.fileStore.FileStore object at 0x7f5ff35ab0d0>> ignored
ip-172-31-22-168: 2016-07-25 00:40:53,874 WARNING: toil.leader: The jobWrapper seems to have left a log file, indicating failure: b/8/job1TULPe
ip-172-31-22-168: 2016-07-25 00:40:53,874 WARNING: toil.leader: Reporting file: b/8/job1TULPe
ip-172-31-22-168: 2016-07-25 00:40:53,874 WARNING: toil.leader: b/8/job1TULPe:	---TOIL WORKER OUTPUT LOG---
ip-172-31-22-168: 2016-07-25 00:40:53,874 WARNING: toil.leader: b/8/job1TULPe:	WARNING:toil.resource:The localize() method should only be invoked on a worker.
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	WARNING:toil.resource:Can't find resource for leader path '/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts'
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages', name='toil_scripts.tools.preprocessing')
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	WARNING:toil.resource:The localize() method should only be invoked on a worker.
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	WARNING:toil.resource:Can't find resource for leader path '/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts'
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages', name='toil_scripts.tools.preprocessing')
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	INFO:toil.fileStore:CACHE: Cache hit on file with ID 't/3/tmpBM7nIk.tmp'.
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	This is cutadapt 1.9 with Python 2.7.6
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	Command line parameters: -a AGATCGGAAGAG -m 35 -o /data/R1.fastq /data/R1.fastq
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	Trimming 1 adapter with at most 10.0% errors in single-end mode ...
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	No reads processed! Either your input file is empty or you used the wrong -f/--format parameter.
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	WARNING:toil.fileStore:the size on record differed from the real size by 25659991688 bytes
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	INFO:toil.fileStore:LOG-TO-MASTER: Successfully deleted local copies of file with ID 't/3/tmpBM7nIk.tmp'.
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	Traceback (most recent call last):
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 330, in main
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	    job._runner(jobWrapper=jobWrapper, jobStore=jobStore, fileStore=fileStore)
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1043, in _runner
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	    returnValues = self._run(jobWrapper, fileStore)
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 991, in _run
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	    return self.run(fileStore)
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1136, in run
ip-172-31-22-168: 2016-07-25 00:40:53,875 WARNING: toil.leader: b/8/job1TULPe:	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
ip-172-31-22-168: 2016-07-25 00:40:53,876 WARNING: toil.leader: b/8/job1TULPe:	  File "/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts/tools/preprocessing.py", line 43, in run_cutadapt
ip-172-31-22-168: 2016-07-25 00:40:53,876 WARNING: toil.leader: b/8/job1TULPe:	    r1_cut_id = job.fileStore.writeGlobalFile(os.path.join(work_dir, 'R1_cutadapt.fastq'))
ip-172-31-22-168: 2016-07-25 00:40:53,876 WARNING: toil.leader: b/8/job1TULPe:	  File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 207, in writeGlobalFile
ip-172-31-22-168: 2016-07-25 00:40:53,876 WARNING: toil.leader: b/8/job1TULPe:	    os.link(absLocalFileName, self.jobStore._getAbsPath(jobStoreFileID))
ip-172-31-22-168: 2016-07-25 00:40:53,876 WARNING: toil.leader: b/8/job1TULPe:	OSError: [Errno 2] No such file or directory
ip-172-31-22-168: 2016-07-25 00:40:53,876 WARNING: toil.leader: b/8/job1TULPe:	Exiting the worker because of a failed jobWrapper on host ip-172-31-22-168
ip-172-31-22-168: 2016-07-25 00:40:53,876 WARNING: toil.leader: b/8/job1TULPe:	ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-22-168
ip-172-31-22-168: 2016-07-25 00:40:53,876 WARNING: toil.leader: b/8/job1TULPe:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job b/8/job1TULPe to 1
ip-172-31-22-168: 2016-07-25 00:40:53,876 INFO: toil.batchSystems.singleMachine: Executing command: '_toil_worker /mnt/ephemeral/rna/jobstore b/8/job1TULPe'.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 1215, in asyncWrite
    raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 1215, in asyncWrite
    raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting

Exception RuntimeError: RuntimeError('cannot join current thread',) in <bound method FileStore.__del__ of <toil.fileStore.FileStore object at 0x7f2492b790d0>> ignored
ip-172-31-22-168: 2016-07-25 00:40:56,091 WARNING: toil.leader: The jobWrapper seems to have left a log file, indicating failure: b/8/job1TULPe
ip-172-31-22-168: 2016-07-25 00:40:56,091 WARNING: toil.leader: Reporting file: b/8/job1TULPe
ip-172-31-22-168: 2016-07-25 00:40:56,091 WARNING: toil.leader: b/8/job1TULPe:	---TOIL WORKER OUTPUT LOG---
ip-172-31-22-168: 2016-07-25 00:40:56,091 WARNING: toil.leader: b/8/job1TULPe:	WARNING:toil.resource:The localize() method should only be invoked on a worker.
ip-172-31-22-168: 2016-07-25 00:40:56,091 WARNING: toil.leader: b/8/job1TULPe:	WARNING:toil.resource:Can't find resource for leader path '/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts'
ip-172-31-22-168: 2016-07-25 00:40:56,091 WARNING: toil.leader: b/8/job1TULPe:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages', name='toil_scripts.tools.preprocessing')
ip-172-31-22-168: 2016-07-25 00:40:56,091 WARNING: toil.leader: b/8/job1TULPe:	WARNING:toil.resource:The localize() method should only be invoked on a worker.
ip-172-31-22-168: 2016-07-25 00:40:56,091 WARNING: toil.leader: b/8/job1TULPe:	WARNING:toil.resource:Can't find resource for leader path '/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts'
ip-172-31-22-168: 2016-07-25 00:40:56,091 WARNING: toil.leader: b/8/job1TULPe:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages', name='toil_scripts.tools.preprocessing')
ip-172-31-22-168: 2016-07-25 00:40:56,091 WARNING: toil.leader: b/8/job1TULPe:	INFO:toil.fileStore:CACHE: Cache hit on file with ID 't/3/tmpBM7nIk.tmp'.
ip-172-31-22-168: 2016-07-25 00:40:56,091 WARNING: toil.leader: b/8/job1TULPe:	This is cutadapt 1.9 with Python 2.7.6
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	Command line parameters: -a AGATCGGAAGAG -m 35 -o /data/R1.fastq /data/R1.fastq
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	Trimming 1 adapter with at most 10.0% errors in single-end mode ...
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	No reads processed! Either your input file is empty or you used the wrong -f/--format parameter.
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	INFO:toil.fileStore:LOG-TO-MASTER: Successfully deleted local copies of file with ID 't/3/tmpBM7nIk.tmp'.
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	Traceback (most recent call last):
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 330, in main
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	    job._runner(jobWrapper=jobWrapper, jobStore=jobStore, fileStore=fileStore)
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1043, in _runner
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	    returnValues = self._run(jobWrapper, fileStore)
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 991, in _run
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	    return self.run(fileStore)
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1136, in run
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	  File "/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts/tools/preprocessing.py", line 43, in run_cutadapt
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	    r1_cut_id = job.fileStore.writeGlobalFile(os.path.join(work_dir, 'R1_cutadapt.fastq'))
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	  File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 207, in writeGlobalFile
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	    os.link(absLocalFileName, self.jobStore._getAbsPath(jobStoreFileID))
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	OSError: [Errno 2] No such file or directory
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	Exiting the worker because of a failed jobWrapper on host ip-172-31-22-168
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-22-168
ip-172-31-22-168: 2016-07-25 00:40:56,092 WARNING: toil.leader: b/8/job1TULPe:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job b/8/job1TULPe to 0
ip-172-31-22-168: 2016-07-25 00:40:56,093 WARNING: toil.leader: Job: b/8/job1TULPe is completely failed
ip-172-31-22-168: 2016-07-25 00:41:02,093 INFO: toil.leader: No jobs left to run so exiting.
ip-172-31-22-168: 2016-07-25 00:41:02,094 INFO: toil.leader: Finished the main loop
ip-172-31-22-168: 2016-07-25 00:41:02,094 INFO: toil.leader: Waiting for stats and logging collator process to finish ...
ip-172-31-22-168: 2016-07-25 00:41:02,198 INFO: toil.leader: ... finished collating stats and logs. Took 0.104333877563 seconds
ip-172-31-22-168: 2016-07-25 00:41:02,198 INFO: toil.leader: Waiting for service manager thread to finish ...
ip-172-31-22-168: 2016-07-25 00:41:02,306 INFO: toil.leader: ... finished shutting down the service manager. Took 0.107571125031 seconds
ip-172-31-22-168: 2016-07-25 00:41:02,306 INFO: toil.leader: Finished toil run with 4 failed jobs
ip-172-31-22-168: 2016-07-25 00:41:02,306 INFO: toil.leader: Failed jobs at end of the run: set(['l/q/job_9Ztlr', 'b/8/job1TULPe', 'U/z/job_XOUhE', 'V/S/job_uReah'])
Traceback (most recent call last):
  File "/home/ubuntu/toil-scripts/bin/toil-rnaseq", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/toil-scripts/local/lib/python2.7/site-packages/toil_scripts/rnaseq_cgl/rnaseq_cgl_pipeline.py", line 506, in main
    Job.Runner.startToil(Job.wrapJobFn(map_job, download_sample, samples, config), args)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 500, in startToil
    return toil.start(job)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 561, in start
    return self._runMainLoop(job)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 775, in _runMainLoop
    jobCache=self._jobCache)
  File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 694, in mainLoop
    raise FailedJobsException( config.jobStore, len(toilState.totalFailedJobs) )
toil.leader.FailedJobsException: The job store '/mnt/ephemeral/rna/jobstore' contains 4 failed jobs

```

**Comment by jvivian** [comment]
@JakeNarkizian — Just confirming, you know this data is unpaired?

**Comment by JakeNarkizian** [comment]
Yes.
