### ISSUE TITLE
exome pipeline failing on import error

### ISSUE THREAD

**Issue by JakeNarkizian** [BD2KGenomics/toil-scripts#395]
## config:
```
# CGL Exome Pipeline configuration file
# This configuration file is formatted in YAML. Simply write the value (at least one space) after the colon.
# Edit the values in this configuration file and then rerun the pipeline: "toil-variant run"
#
# URLs can take the form: http://, file://, s3://, gnos://
# Local inputs follow the URL convention: file:///full/path/to/input
# S3 URLs follow the convention: s3://bucket/directory/file.txt
#
# Comments (beginning with #) do not need to be removed. Optional parameters left blank are treated as false.
####################################################################################################################
# Required: URL to reference genome
reference: s3://cgl-pipeline-inputs/variant_hg19/hg19.fa

# Required: URL to phase indels VCF
phase: s3://cgl-pipeline-inputs/variant_hg19/1000G_phase1.indels.hg19.sites.vcf

# Required: URL to Mills indel VCF
mills: s3://cgl-pipeline-inputs/variant_hg19/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf

# Required: URL to dbsnp VCF
dbsnp: s3://cgl-pipeline-inputs/variant_hg19/dbsnp_138.hg19.vcf

# Required: URL to cosmic VCF
cosmic: s3://cgl-pipeline-inputs/variant_hg19/cosmic.hg19.vcf

# Required: Output location of sample. Can be full path to a directory or an s3:// URL
# Warning: S3 buckets must exist prior to upload or it will fail.
output-dir: s3://hnarkizi-pipeline-test/exome-mult-pip

# Optional: If true, will run MuTect to do mutation calls
run-mutect: true

# Optional: If true, will run pindel to analyze indel
run-pindel: true

# Optional: If true, will run MuSe to do mutation calls
run-muse: true

# Optional: If true, will perform indel realignment and base quality score recalibration
preprocessing: true

# Optional: Provide a full path to a 32-byte key used for SSE-C Encryption in Amazon
ssec: /home/mesosbox/shared/shared/master.key 

# Optional: Provide a full path to a CGHub Key used to access GNOS hosted data
gtkey:

# Optional: If true, uses resource requirements appropriate for continuous integration
ci-test: 
```

## manifest:
```
#   Edit this manifest to include information pertaining to each sample pair to be run.
#   There are 3 tab-separated columns: UUID, Normal BAM URL, Tumor BAM URL
#
#   UUID            This should be a unique identifier for the sample to be processed
#   Normal URL      A URL (http://, file://, s3://, gnos://) pointing to the normal bam
#   Tumor URL       A URL (http://, file://, s3://, gnos://) pointing to the tumor bam
#
#   Examples of several combinations are provided below. Lines beginning with # are ignored.
#
#   UUID_1  file:///path/to/normal.bam  file:///path/to/tumor.bam
#   UUID_2  http://sample-depot.com/normal.bam  http://sample-depot.com/tumor.bam
#   UUID_3  s3://my-bucket-name/directory/normal.bam    file:///path/to/tumor.bam
#
#   Place your samples below, one per line.
jake-test-bluegreen	s3://cgl-driver-projects-encrypted/ucsf-pnoc/ucsf_issue52_input/DTB-005-BL-T-DNA-HSmerge_S1.bam	s3://cgl-driver-projects-encrypted/ucsf-pnoc/ucsf_issue52_input/DTB-005-N-DNA-HS1_S1.bam
```

## log:
```
ip-172-31-16-108: 2016-07-29 22:02:49,571 INFO: toil.jobStores.abstractJobStore: Checking job graph connectivity...
ip-172-31-16-108: 2016-07-29 22:02:49,602 INFO: toil.jobStores.abstractJobStore: 1 jobs reachable from root.
ip-172-31-16-108: 2016-07-29 22:02:49,602 CRITICAL: toil.jobStores.abstractJobStore: Repairing job: 0b791186-5cb4-418d-9083-b2d1a1c45644
ip-172-31-16-108: 2016-07-29 22:02:49,643 INFO: toil.jobStores.abstractJobStore: Discarding old statistics and logs...
ip-172-31-16-108: 2016-07-29 22:02:49,689 INFO: toil.jobStores.abstractJobStore: Job store is clean
ip-172-31-16-108: 2016-07-29 22:02:49,718 INFO: toil.realtimeLogger: Real-time logging disabled
ip-172-31-16-108: 2016-07-29 22:02:49,720 INFO: toil.leader: (Re)building internal scheduler state
ip-172-31-16-108: 2016-07-29 22:02:49,720 INFO: toil.leader: Checked batch system has no running jobs and no updated jobs
ip-172-31-16-108: 2016-07-29 22:02:49,720 INFO: toil.leader: Found 1 jobs to start and 0 jobs with successors to run
ip-172-31-16-108: 2016-07-29 22:02:49,723 INFO: toil.leader: Starting the main loop
ip-172-31-16-108: 2016-07-29 22:02:54,544 INFO: toil.batchSystems.mesos.batchSystem: Preparing to launch Mesos task 0 using offer ab6b2e9a-0c1f-40ee-91d9-2dfa92abf5ee-O14 ...
ip-172-31-16-108: 2016-07-29 22:02:54,563 INFO: toil.batchSystems.mesos.batchSystem: Launched Mesos task 0.
ip-172-31-16-108: 2016-07-29 22:04:20,106 WARNING: toil.leader: The jobWrapper seems to have left a log file, indicating failure: 0b791186-5cb4-418d-9083-b2d1a1c45644
ip-172-31-16-108: 2016-07-29 22:04:20,140 WARNING: toil.leader: Reporting file: 0b791186-5cb4-418d-9083-b2d1a1c45644
ip-172-31-16-108: 2016-07-29 22:04:20,140 WARNING: toil.leader: 0b791186-5cb4-418d-9083-b2d1a1c45644:	---TOIL WORKER OUTPUT LOG---
ip-172-31-16-108: 2016-07-29 22:04:20,141 WARNING: toil.leader: 0b791186-5cb4-418d-9083-b2d1a1c45644:	WARNING:toil.resource:The localize() method should only be invoked on a worker.
ip-172-31-16-108: 2016-07-29 22:04:20,141 WARNING: toil.leader: 0b791186-5cb4-418d-9083-b2d1a1c45644:	WARNING:toil.resource:Can't find resource for leader path '/home/mesosbox/toil-scripts/local/lib/python2.7/site-packages/toil_scripts'
ip-172-31-16-108: 2016-07-29 22:04:20,141 WARNING: toil.leader: 0b791186-5cb4-418d-9083-b2d1a1c45644:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/home/mesosbox/toil-scripts/local/lib/python2.7/site-packages', name='toil_scripts.exome_variant_pipeline.exome_variant_pipeline')
ip-172-31-16-108: 2016-07-29 22:04:20,141 WARNING: toil.leader: 0b791186-5cb4-418d-9083-b2d1a1c45644:	ERROR:toil.job:Failed to import user module ModuleDescriptor(dirPath='/home/mesosbox/toil-scripts/local/lib/python2.7/site-packages', name='toil_scripts.exome_variant_pipeline.exome_variant_pipeline') from sys.path=['/usr/local/bin', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages/mesos-0.25.0-py2.7-linux-x86_64.egg', '/usr/local/lib/python2.7/dist-packages/mesos.interface-0.25.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/google_common-0.0.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages', '/usr/local/lib/python2.7/dist-packages/protobuf-2.6.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/setuptools-25.1.0-py2.7.egg', '/usr/lib/python2.7/dist-packages', '/home/mesosbox/toil-scripts/local/lib/python2.7/site-packages']
ip-172-31-16-108: 2016-07-29 22:04:20,141 WARNING: toil.leader: 0b791186-5cb4-418d-9083-b2d1a1c45644:	Traceback (most recent call last):
ip-172-31-16-108: 2016-07-29 22:04:20,141 WARNING: toil.leader: 0b791186-5cb4-418d-9083-b2d1a1c45644:	  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 316, in main
ip-172-31-16-108: 2016-07-29 22:04:20,141 WARNING: toil.leader: 0b791186-5cb4-418d-9083-b2d1a1c45644:	    job = Job._loadJob(jobWrapper.command, jobStore)
ip-172-31-16-108: 2016-07-29 22:04:20,142 WARNING: toil.leader: 0b791186-5cb4-418d-9083-b2d1a1c45644:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 624, in _loadJob
ip-172-31-16-108: 2016-07-29 22:04:20,142 WARNING: toil.leader: 0b791186-5cb4-418d-9083-b2d1a1c45644:	    userModule = cls._loadUserModule(userModule)
ip-172-31-16-108: 2016-07-29 22:04:20,142 WARNING: toil.leader: 0b791186-5cb4-418d-9083-b2d1a1c45644:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 598, in _loadUserModule
ip-172-31-16-108: 2016-07-29 22:04:20,142 WARNING: toil.leader: 0b791186-5cb4-418d-9083-b2d1a1c45644:	    return importlib.import_module(userModule.name)
ip-172-31-16-108: 2016-07-29 22:04:20,142 WARNING: toil.leader: 0b791186-5cb4-418d-9083-b2d1a1c45644:	  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
ip-172-31-16-108: 2016-07-29 22:04:20,142 WARNING: toil.leader: 0b791186-5cb4-418d-9083-b2d1a1c45644:	    __import__(name)
ip-172-31-16-108: 2016-07-29 22:04:20,142 WARNING: toil.leader: 0b791186-5cb4-418d-9083-b2d1a1c45644:	ImportError: No module named toil_scripts.exome_variant_pipeline.exome_variant_pipeline
ip-172-31-16-108: 2016-07-29 22:04:20,142 WARNING: toil.leader: 0b791186-5cb4-418d-9083-b2d1a1c45644:	Exiting the worker because of a failed jobWrapper on host ip-172-31-27-175
ip-172-31-16-108: 2016-07-29 22:04:20,142 WARNING: toil.leader: 0b791186-5cb4-418d-9083-b2d1a1c45644:	ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-27-175
ip-172-31-16-108: 2016-07-29 22:04:20,143 WARNING: toil.leader: 0b791186-5cb4-418d-9083-b2d1a1c45644:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job 0b791186-5cb4-418d-9083-b2d1a1c45644 to 0
ip-172-31-16-108: 2016-07-29 22:04:20,143 WARNING: toil.leader: Job: 0b791186-5cb4-418d-9083-b2d1a1c45644 is completely failed
ip-172-31-16-108: 2016-07-29 22:04:20,143 INFO: toil.leader: No jobs left to run so exiting.
ip-172-31-16-108: 2016-07-29 22:04:20,143 INFO: toil.leader: Finished the main loop
ip-172-31-16-108: 2016-07-29 22:04:20,143 INFO: toil.leader: Waiting for stats and logging collator process to finish ...
ip-172-31-16-108: 2016-07-29 22:04:20,564 INFO: toil.leader: ... finished collating stats and logs. Took 0.420853853226 seconds
ip-172-31-16-108: 2016-07-29 22:04:20,564 INFO: toil.leader: Waiting for service manager thread to finish ...
ip-172-31-16-108: 2016-07-29 22:04:20,738 INFO: toil.leader: ... finished shutting down the service manager. Took 0.173075914383 seconds
ip-172-31-16-108: 2016-07-29 22:04:20,750 INFO: toil.leader: Finished toil run with 1 failed jobs
ip-172-31-16-108: 2016-07-29 22:04:20,751 INFO: toil.leader: Failed jobs at end of the run: set(['0b791186-5cb4-418d-9083-b2d1a1c45644'])
ip-172-31-16-108: 2016-07-29 22:04:20,751 INFO: toil.batchSystems.mesos.batchSystem: Stopping Mesos driver
I0729 22:04:20.751528  2130 sched.cpp:1771] Asked to stop the driver
I0729 22:04:20.751677  2139 sched.cpp:1040] Stopping framework 'ab6b2e9a-0c1f-40ee-91d9-2dfa92abf5ee-0001'
ip-172-31-16-108: 2016-07-29 22:04:20,751 INFO: toil.batchSystems.mesos.batchSystem: Joining Mesos driver
ip-172-31-16-108: 2016-07-29 22:04:20,751 INFO: toil.batchSystems.mesos.batchSystem: Joined Mesos driver
Traceback (most recent call last):
  File "/home/mesosbox/toil-scripts/bin/toil-exome", line 11, in <module>
    sys.exit(main())
  File "/home/mesosbox/toil-scripts/local/lib/python2.7/site-packages/toil_scripts/exome_variant_pipeline/exome_variant_pipeline.py", line 424, in main
    Job.Runner.startToil(Job.wrapJobFn(download_shared_files, samples, config), args)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 502, in startToil
    return toil.restart()
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 584, in restart
    return self._runMainLoop(rootJob)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 775, in _runMainLoop
    jobCache=self._jobCache)
  File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 694, in mainLoop
    raise FailedJobsException( config.jobStore, len(toilState.totalFailedJobs) )
toil.leader.FailedJobsException: The job store 'aws:us-west-2:hnarkizi-test-bluegreen' contains 1 failed jobs
```

**Comment by jvivian** [comment]
I'll take a look at this when I can, but this doesn't look like a pipeline error.

**Comment by jvivian** [comment]
@JakeNarkizian — I couldn't replicate this on single machine after a fresh venv and install of toil and toil-scripts.

**Comment by jvivian** [comment]
@JakeNarkizian — Can you confirm error from fresh venv install? If not please close.

**Comment by JakeNarkizian** [comment]
@jvivian could not reproduce on fresh cluster. See [core-operations #58](https://github.com/BD2KGenomics/core-operations/issues/58).
