### ISSUE TITLE
toil-bwa fails on local genome input

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/toil-scripts#396]
I am trying to run toil-bwa on a local copy of hg19. I did not create any of the 'optional' files. 
This is in the config.yaml:
`ref: file:///home/ubuntu/data/hg19.fa`

Command:
`toil-bwa run /home/ubuntu/bwa_test1/jobstore --workDir=/home/ubuntu/bwa_test1/workdir --config config.yaml --manifest bwaManifest.tsv`
[This config file works](http://hgwdev.cse.ucsc.edu/~jeltje/toil/config4.yaml)
[But this one fails](http://hgwdev.cse.ucsc.edu/~jeltje/toil/config5.yaml)
[manifest file](http://hgwdev.cse.ucsc.edu/~jeltje/toil/bwaManifest5.tsv) for both runs

[full error log here](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.5)

Stack trace:
```
Traceback (most recent call last):
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/toil/worker.py", line 330, in main
    job._runner(jobWrapper=jobWrapper, jobStore=jobStore, fileStore=fileStore)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/toil/job.py", line 1043, in _runner
    returnValues = self._run(jobWrapper, fileStore)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/toil/job.py", line 991, in _run
    return self.run(fileStore)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/toil/job.py", line 1136, in run
    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/toil_scripts/lib/urls.py", line 40, in download_url_job
    s3_key_path=s3_key_path, cghub_key_path=cghub_key_path)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/toil_scripts/lib/urls.py", line 23, in download_url
    file_path = os.path.join(work_dir, name) if name else os.path.join(work_dir, os.path.basename(url))
  File "/home/ubuntu/venv/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by jvivian** [comment]
Thanks for the great info! I'll look into this ASAP.

**Comment by jvivian** [comment]
@Jeltje — In the future, please assign these to me when you open them so it doesn't get lost.  Found the issue, rolling out a fix now.
