### ISSUE TITLE
toil-bwa requires boto and something else

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/toil-scripts#400]
Using version 
`toil (3.5.0a1.dev229)`
`toil-scripts (2.1.0a1.dev478)`
Inputs identical to issue 396, except with the master key removed from the config file:
`ssec:`
Note that boto isn't specicically listed as a requirement, and I don't do anything that should need password access to AWS

Full error:
```
jeltje-vm 2016-08-02 14:48:47,998 MainThread INFO toil.lib.bioio: Logging set at level: INFO
jeltje-vm 2016-08-02 14:48:47,998 MainThread INFO toil.lib.bioio: Logging set at level: INFO
jeltje-vm 2016-08-02 14:48:48,001 MainThread INFO toil.jobStores.fileJobStore: Path to job store directory is '/home/ubuntu/bwa_test1/jobstore'.
jeltje-vm 2016-08-02 14:48:48,001 MainThread INFO toil.jobStores.abstractJobStore: The workflow ID is: 'd232509d-4063-46de-b73a-92287031c55c'
jeltje-vm 2016-08-02 14:48:48,004 MainThread INFO toil.common: Using the single machine batch system
jeltje-vm 2016-08-02 14:48:48,004 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxCores to CPU count of system (8).
jeltje-vm 2016-08-02 14:48:48,004 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxMemory to physically available memory (16827285504).
jeltje-vm 2016-08-02 14:48:48,004 MainThread INFO toil.common: Created the workflow directory at /home/ubuntu/bwa_test1/workdir/toil-d232509d-4063-46de-b73a-92287031c55c
jeltje-vm 2016-08-02 14:48:48,004 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxDisk to physically available disk (96972509184).
jeltje-vm 2016-08-02 14:48:48,005 MainThread INFO toil.batchSystems.singleMachine: Setting up the thread pool with 80 workers, given a minimum CPU fraction of 0.100000 and a maximum CPU value of 8.
jeltje-vm 2016-08-02 14:48:48,037 MainThread INFO toil.common: Written the environment for the jobs to the environment file
jeltje-vm 2016-08-02 14:48:48,037 MainThread INFO toil.common: Caching all jobs in job store
jeltje-vm 2016-08-02 14:48:48,037 MainThread INFO toil.common: 0 jobs downloaded.
jeltje-vm 2016-08-02 14:48:48,042 MainThread INFO toil.realtimeLogger: Real-time logging disabled
Traceback (most recent call last):
  File "/home/ubuntu/venvs/bwa/bin/toil-bwa", line 9, in <module>
    load_entry_point('toil-scripts==2.1.0a1.dev478', 'console_scripts', 'toil-bwa')()
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil_scripts/bwa_alignment/bwa_alignment.py", line 287, in main
    Job.Runner.startToil(Job.wrapJobFn(download_reference_files, config, samples), args)
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/job.py", line 542, in startToil
    return toil.start(job)
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/common.py", line 580, in start
    return self._runMainLoop(job)
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/common.py", line 788, in _runMainLoop
    from toil.leader import mainLoop
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/leader.py", line 34, in <module>
    from toil.jobStores.aws.jobStore import AWSJobStore
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/jobStores/aws/jobStore.py", line 34, in <module>
    from boto.sdb.domain import Domain
ImportError: No module named boto.sdb.domain
```

I tried to install boto (v 2.42.0)
and then got a whole new error:
```
jeltje-vm 2016-08-02 14:55:57,739 MainThread INFO toil.lib.bioio: Logging set at level: INFO
jeltje-vm 2016-08-02 14:55:57,739 MainThread INFO toil.lib.bioio: Logging set at level: INFO
jeltje-vm 2016-08-02 14:55:57,743 MainThread INFO toil.jobStores.fileJobStore: Path to job store directory is '/home/ubuntu/bwa_test1/jobstore'.
jeltje-vm 2016-08-02 14:55:57,743 MainThread INFO toil.jobStores.abstractJobStore: The workflow ID is: '84837dba-a974-4db9-a7fe-c7fa53850360'
jeltje-vm 2016-08-02 14:55:57,747 MainThread INFO toil.common: Using the single machine batch system
jeltje-vm 2016-08-02 14:55:57,747 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxCores to CPU count of system (8).
jeltje-vm 2016-08-02 14:55:57,747 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxMemory to physically available memory (16827285504).
jeltje-vm 2016-08-02 14:55:57,747 MainThread INFO toil.common: Created the workflow directory at /home/ubuntu/bwa_test1/workdir/toil-84837dba-a974-4db9-a7fe-c7fa53850360
jeltje-vm 2016-08-02 14:55:57,747 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxDisk to physically available disk (96961081344).
jeltje-vm 2016-08-02 14:55:57,748 MainThread INFO toil.batchSystems.singleMachine: Setting up the thread pool with 80 workers, given a minimum CPU fraction of 0.100000 and a maximum CPU value of 8.
jeltje-vm 2016-08-02 14:55:57,768 MainThread INFO toil.common: Written the environment for the jobs to the environment file
jeltje-vm 2016-08-02 14:55:57,768 MainThread INFO toil.common: Caching all jobs in job store
jeltje-vm 2016-08-02 14:55:57,768 MainThread INFO toil.common: 0 jobs downloaded.
jeltje-vm 2016-08-02 14:55:57,774 MainThread INFO toil.realtimeLogger: Real-time logging disabled
Traceback (most recent call last):
  File "/home/ubuntu/venvs/bwa/bin/toil-bwa", line 9, in <module>
    load_entry_point('toil-scripts==2.1.0a1.dev478', 'console_scripts', 'toil-bwa')()
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil_scripts/bwa_alignment/bwa_alignment.py", line 287, in main
    Job.Runner.startToil(Job.wrapJobFn(download_reference_files, config, samples), args)
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/job.py", line 542, in startToil
    return toil.start(job)
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/common.py", line 580, in start
    return self._runMainLoop(job)
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/common.py", line 788, in _runMainLoop
    from toil.leader import mainLoop
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/leader.py", line 34, in <module>
    from toil.jobStores.aws.jobStore import AWSJobStore
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/jobStores/aws/jobStore.py", line 44, in <module>
    from concurrent.futures import ThreadPoolExecutor
ImportError: No module named concurrent.futures
```
I don't know if this is the toil module? In the previous version I worked with 
`toil (3.4.0a1.dev219)`
`toil-scripts (2.1.0a1.dev478)`

**Comment by jvivian** [comment]
> Using version 
> toil (3.5.0a1.dev229)
> toil-scripts (2.1.0a1.dev478)

Why test the development versions? I don't get this issue on release versions:

```
virtualenv ~/toil-scripts
source ~/toil-scripts/bin/activate
pip install toil
pip install toil-scripts
toil-bwa generate
toil-bwa run ./jobStore --workDir=/data
```

It's good that you noticed this, because I'm not sure why Toil (on master) is pulling in the AWS jobstore when you're running in local mode

```
 File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/job.py", line 542, in startToil
    return toil.start(job)
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/common.py", line 580, in start
    return self._runMainLoop(job)
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/common.py", line 788, in _runMainLoop
    from toil.leader import mainLoop
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/leader.py", line 34, in <module>
    from toil.jobStores.aws.jobStore import AWSJobStore
```
@cket — Since Hannes and I are on vacation, you mind taking a look at this? I'm going to close this ticket but @Jeltje opened one under BD2KGenomics/toil#1104

**Comment by Jeltje** [comment]
@jvivian I tried using the stable version of toil but that didn't work with toil-scripts. So I figured I'd take the dev version and that worked fine with the first toil-bwa I tried.
