### ISSUE TITLE
toil-bwa (probably) expects s3_key_path for local files

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/toil-scripts#403]
I'm running locally, with this in the config.yaml:
```
ref: file:///home/ubuntu/data/hg19.fa
output-dir: /home/ubuntu/bwa_test1/bamout5
```
and in the manifest:
`small   file:///home/ubuntu/bwa_test1/testinput/small.fastq.gz`

The error appears to come from download_url, so I think the program is trying to do an unnecessary download...?
```
        Traceback (most recent call last):
          File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/worker.py", line 330, in main
            job._runner(jobWrapper=jobWrapper, jobStore=jobStore, fileStore=fileStore)
          File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/job.py", line 1043, in _runner
            returnValues = self._run(jobWrapper, fileStore)
          File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/job.py", line 991, in _run
            return self.run(fileStore)
          File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/job.py", line 1136, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil_scripts/lib/urls.py", line 40, in download_url_job
            s3_key_path=s3_key_path, cghub_key_path=cghub_key_path)
          File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil_scripts/lib/urls.py", line 23, in download_url
            file_path = os.path.join(work_dir, name) if name else os.path.join(work_dir, os.path.basename(url))
          File "/home/ubuntu/venvs/bwa/lib/python2.7/posixpath.py", line 114, in basename
            i = p.rfind('/') + 1
        AttributeError: 'NoneType' object has no attribute 'rfind'
```
Versions:
```
bd2k-python-lib (1.14a1.dev29)
boto (2.42.0)
dill (0.2.5)
pip (8.1.2)
PyYAML (3.11)
setuptools (12.2)
toil (3.3.1)
toil-scripts (2.1.0a1.dev478)
tqdm (3.8.0)
```

[full log](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.8)
[config file](http://hgwdev.cse.ucsc.edu/~jeltje/toil/config5.yaml)
[manifest](http://hgwdev.cse.ucsc.edu/~jeltje/toil/bwaManifest5.tsv)

**Comment by jvivian** [comment]
Please open tickets for release versions (ex: **2.0.5**) not development versions: **2.1.0a1.dev478**.  I think this particular issue was addressed here: https://github.com/BD2KGenomics/toil-scripts/pull/397
