### ISSUE TITLE
Mate pair designator heuristic fails if parent directory name contains R1 or R2

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-scripts#436]
From http://jenkins.cgcloud.info/job/toil-pull-request-integration-tests/78/testReport/junit/src.toil.test.provisioners.cgcloud.provisionerTest/CGCloudProvisionerTest/testStaticCluster/:

```
ip-172-31-21-199 2016-09-02 04:12:14,899 MainThread WARNING toil.leader: 90fb8c31-9a23-41c9-a383-abf39615a8c3:	Traceback (most recent call last):
ip-172-31-21-199 2016-09-02 04:12:14,899 MainThread WARNING toil.leader: 90fb8c31-9a23-41c9-a383-abf39615a8c3:	  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 331, in main
ip-172-31-21-199 2016-09-02 04:12:14,899 MainThread WARNING toil.leader: 90fb8c31-9a23-41c9-a383-abf39615a8c3:	    job._runner(jobWrapper=jobWrapper, jobStore=jobStore, fileStore=fileStore)
ip-172-31-21-199 2016-09-02 04:12:14,899 MainThread WARNING toil.leader: 90fb8c31-9a23-41c9-a383-abf39615a8c3:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1085, in _runner
ip-172-31-21-199 2016-09-02 04:12:14,899 MainThread WARNING toil.leader: 90fb8c31-9a23-41c9-a383-abf39615a8c3:	    returnValues = self._run(jobWrapper, fileStore)
ip-172-31-21-199 2016-09-02 04:12:14,899 MainThread WARNING toil.leader: 90fb8c31-9a23-41c9-a383-abf39615a8c3:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1033, in _run
ip-172-31-21-199 2016-09-02 04:12:14,899 MainThread WARNING toil.leader: 90fb8c31-9a23-41c9-a383-abf39615a8c3:	    return self.run(fileStore)
ip-172-31-21-199 2016-09-02 04:12:14,899 MainThread WARNING toil.leader: 90fb8c31-9a23-41c9-a383-abf39615a8c3:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1178, in run
ip-172-31-21-199 2016-09-02 04:12:14,899 MainThread WARNING toil.leader: 90fb8c31-9a23-41c9-a383-abf39615a8c3:	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
ip-172-31-21-199 2016-09-02 04:12:14,899 MainThread WARNING toil.leader: 90fb8c31-9a23-41c9-a383-abf39615a8c3:	  File "/tmp/pip-build-EwMPRA/toil-scripts/toil_scripts/rnaseq_cgl/rnaseq_cgl_pipeline.py", line 201, in process_sample_tar
ip-172-31-21-199 2016-09-02 04:12:14,900 MainThread WARNING toil.leader: 90fb8c31-9a23-41c9-a383-abf39615a8c3:	  File "/tmp/pip-build-EwMPRA/toil-scripts/toil_scripts/lib/__init__.py", line 44, in require
ip-172-31-21-199 2016-09-02 04:12:14,900 MainThread WARNING toil.leader: 90fb8c31-9a23-41c9-a383-abf39615a8c3:	UserError: 
ip-172-31-21-199 2016-09-02 04:12:14,900 MainThread WARNING toil.leader: 90fb8c31-9a23-41c9-a383-abf39615a8c3:	
ip-172-31-21-199 2016-09-02 04:12:14,900 MainThread WARNING toil.leader: 90fb8c31-9a23-41c9-a383-abf39615a8c3:	Check fastq naming, uneven number of pairs found: r1: ['/var/lib/toil/toil-d4a0309f-4911-495e-a6ca-2d599eea49f7/tmpI63wE8/244bcf83-c584-4098-9109-96665b1c4972/tR2afmv/R1.fq.gz'], r2: ['/var/lib/toil/toil-d4a0309f-4911-495e-a6ca-2d599eea49f7/tmpI63wE8/244bcf83-c584-4098-9109-96665b1c4972/tR2afmv/R1.fq.gz', '/var/lib/toil/toil-d4a0309f-4911-495e-a6ca-2d599eea49f7/tmpI63wE8/244bcf83-c584-4098-9109-96665b1c4972/tR2afmv/R2.fq.gz', '/var/lib/toil/toil-d4a0309f-4911-495e-a6ca-2d599eea49f7/tmpI63wE8/244bcf83-c584-4098-9109-96665b1c4972/tR2afmv/sample.tar']
```

Note how the directory name `tR2afmv` contains the string `R2` which throws off the heuristic.

**Comment by fnothaft** [comment]
Nice! I know where this one came from...

**Comment by jvivian** [comment]
Guilty! Thanks for making a ticket.

**Comment by rcurrie** [comment]
(Moving the discussion about naming pairs from the stanford task here)

Making the hueristic a bit more deterministic ala the regex mentioned:
 /.+?[._-]R?([1])(.fastq(.gz)?|.fq(.gz)?)$/

sounds like a good step in the convention over configuration school of design.

I'd also like to come up with a standard way to specify inputs where the name is not depended on in any way with an eye towards automated systems to ingest, process, and forward. For example if one of two fastq pairs is sent to Treehouse by the partner or one of our systems uploading it to s3 then we should be able to kick off a toil run and point to

s3.amazonaws.com/<bucketname>/c7/96/c7964be8ab814bed8279f75e8e8a5041

as one of the pairs. Alternately if someone sends us the pairs in a tar file we'd need to be able to specify within the tar. There I could see requiring some sort of naming convention on the partners end as they'll have to specify to Treehouse somehow. Key though is to avoid having to download and tar up separate files, rename them somehow in s3, or download and untar only to re-tar...

**Comment by jvivian** [comment]
@rcurrie Part of accepting outside data could be writing a script that does the tarball/recombine before upload.  This way only R1/R2 pairs are passed into the pipeline and we can remove this kludgy step from production.
