### ISSUE TITLE
rnaseq-cgl non fatal? samtools error

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/toil-scripts#460]
```
toil (3.3.0)
toil-scripts (2.0.10)
```

During the by now infamous [ckcc77 run](https://github.com/BD2KGenomics/core-operations/issues/77#issuecomment-246867678) we kept getting errors like this: 

`samtools sort -@ 32 -m 1G rsem.transcript.bam rsem.transcript.sorted" failed! Plase check if you provide correct parameters/options for the pipeline!`
This appears to come from the rsem run. Log context:
```
        rsem-parse-alignments /data/rsem_ref_hg38/hg38 rsem.temp/rsem rsem.stat/rsem b /data/transcriptome.bam -t 2 -tag XM -q

        rsem-build-read-index 32 0 1 rsem.temp/rsem_alignable_1.fa rsem.temp/rsem_alignable_2.fa

        rsem-run-em /data/rsem_ref_hg38/hg38 2 rsem rsem.temp/rsem rsem.stat/rsem -p 32 -b b /data/transcriptome.bam 0 -q
        Time Used for EM.cpp : 1 h 50 m 37 s

        samtools sort -@ 32 -m 1G rsem.transcript.bam rsem.transcript.sorted
        "samtools sort -@ 32 -m 1G rsem.transcript.bam rsem.transcript.sorted" failed! Plase check if you provide correct parameters/options for the pipeline!
        INFO:toil.fileStore:LOG-TO-MASTER: Successfully deleted local copies of file with ID '032b587e-619d-4300-ba5d-5163c8c37e9f'.
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 330, in main
            job._runner(jobWrapper=jobWrapper, jobStore=jobStore, fileStore=fileStore)
          File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1043, in _runner
            returnValues = self._run(jobWrapper, fileStore)
          File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 991, in _run
            return self.run(fileStore)
          File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1136, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/home/mesosbox/toilscripts/local/lib/python2.7/site-packages/toil_scripts/tools/quantifiers.py", line 86, in run_rsem
            parameters=parameters, work_dir=work_dir)
          File "/home/mesosbox/toilscripts/local/lib/python2.7/site-packages/toil_scripts/lib/programs.py", line 105, in docker_call
            _fix_permissions(base_docker_call, tool, work_dir)
          File "/home/mesosbox/toilscripts/local/lib/python2.7/site-packages/toil_scripts/lib/programs.py", line 100, in docker_call
            subprocess.check_call(docker_call)
          File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
            raise CalledProcessError(retcode, cmd)
        CalledProcessError: Command '['docker', 'run', '--log-driver=none', '-v', '/var/lib/toil/toil-afcdd3cf-4072-4eb5-b5f6-3c77f5b17944/tmpsg2bxW/636db7bf-c865-4bc2-9e41-01b307672ab3/tuHPhdr:/data', '--rm', 'quay.io/ucsc_cgl/rsem:1.2.25--d4275175cc8df36967db460b06337a14f40d2f21', '--paired-end', '--quiet', '--no-qualities', '-p', '32', '--forward-prob', '0.5', '--seed-length', '25', '--fragment-length-mean', '-1.0', '--bam', '/data/transcriptome.bam', '/data/rsem_ref_hg38/hg38', 'rsem']' returned non-zero exit status 255
        Exiting the worker because of a failed jobWrapper on host ip-172-31-43-201
        ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-43-201
        WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job 769d32f1-df07-4c32-9e6c-09c1dfd8575d to 2
```
It is not clear from which sample this error came, but the last rerun of these samples (where all but one succeeded) did not show this error, see [tr_log5.txt](https://github.com/BD2KGenomics/toil-scripts/files/475324/tr_log5.txt). So this is either not reproducible or not fatal to the run.

Note also that the `samtools` warning contains the word 'failed' but is not propagated as an `Error` so it's much harder to find in the log (`grep -i error` has been a pretty reliable way to find issues).

[tr_log4.txt](https://github.com/BD2KGenomics/toil-scripts/files/475316/tr_log4.txt)
[trconfig.txt](https://github.com/BD2KGenomics/toil-scripts/files/475317/trconfig.txt)
[trmanifest.txt](https://github.com/BD2KGenomics/toil-scripts/files/475318/trmanifest.txt)

**Comment by jvivian** [comment]
Not really sure what I can do about this issue — I'd need a reliable way to reproduce it.

**Comment by Jeltje** [comment]
I'm guessing the misspelling of the word 'Please' in the statement is also not yours :-)

**Comment by jvivian** [comment]
Nope lol

**Comment by jvivian** [comment]
Was this reproduced in the latest 77 run?

**Comment by Jeltje** [comment]
It was not. I wonder if it has something to do with the disk full errors.

**Comment by jvivian** [comment]
Please reopen if this shows up again.
