### ISSUE TITLE
 rnaseq_unc_pipeline.py get No Such File from mapsplice

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/toil-scripts#84]
This is for commit 8058e7086cdd6f9870de3964252e795d4f4104f4
which is not the very latest one from 20 hours ago, but that change was only to s3am upload, I think.

Running this on a c3.8xlarge mesos cluster. 
The job dies on ` return_input_paths(job, work_dir, ids, 'ebwt.zip', 'chromosomes.zip')` in mapsplice.
I checked, and the files do get downloaded.

[see here for the full debug log](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log)
[and here for the launch script](http://hgwdev.cse.ucsc.edu/~jeltje/toil/launch_zygosity_hg19_mesos.sh) and [config file](http://hgwdev.cse.ucsc.edu/~jeltje/toil/pnoc_rnaseq.config)

Relevant warnings:

```
WARNING:toil.leader:fd6b1a39-156e-4680-a8ce-4c6f29e5ab37:       Traceback (most recent call last):
WARNING:toil.leader:fd6b1a39-156e-4680-a8ce-4c6f29e5ab37:         File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 282, in main
WARNING:toil.leader:fd6b1a39-156e-4680-a8ce-4c6f29e5ab37:           fileStore=fileStore)
WARNING:toil.leader:fd6b1a39-156e-4680-a8ce-4c6f29e5ab37:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1281, in _execute
WARNING:toil.leader:fd6b1a39-156e-4680-a8ce-4c6f29e5ab37:           returnValues = self.run(fileStore)
WARNING:toil.leader:fd6b1a39-156e-4680-a8ce-4c6f29e5ab37:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1383, in run
WARNING:toil.leader:fd6b1a39-156e-4680-a8ce-4c6f29e5ab37:           rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
WARNING:toil.leader:fd6b1a39-156e-4680-a8ce-4c6f29e5ab37:         File "/home/mesosbox/rnaseq_unc_pipeline.py", line 432, in mapsplice
WARNING:toil.leader:fd6b1a39-156e-4680-a8ce-4c6f29e5ab37:         File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
WARNING:toil.leader:fd6b1a39-156e-4680-a8ce-4c6f29e5ab37:           retcode = call(*popenargs, **kwargs)
WARNING:toil.leader:fd6b1a39-156e-4680-a8ce-4c6f29e5ab37:         File "/usr/lib/python2.7/subprocess.py", line 522, in call
WARNING:toil.leader:fd6b1a39-156e-4680-a8ce-4c6f29e5ab37:           return Popen(*popenargs, **kwargs).wait()
WARNING:toil.leader:fd6b1a39-156e-4680-a8ce-4c6f29e5ab37:         File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
WARNING:toil.leader:fd6b1a39-156e-4680-a8ce-4c6f29e5ab37:           errread, errwrite)
WARNING:toil.leader:fd6b1a39-156e-4680-a8ce-4c6f29e5ab37:         File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
WARNING:toil.leader:fd6b1a39-156e-4680-a8ce-4c6f29e5ab37:           raise child_exception
WARNING:toil.leader:fd6b1a39-156e-4680-a8ce-4c6f29e5ab37:       OSError: [Errno 2] No such file or directory
```
In the log file, there are a lot of
```
DEBUG:toil.batchSystems.mesos.batchSystem:Declining offers
DEBUG:toil.batchSystems.mesos.batchSystem:No jobs to assign. Rejecting offer
```

**Comment by Jeltje** [comment]
I just realized I created the toil cluster using cgcloud v1.2.2, I'm not sure if that leads to different versions of programs than using v1.3?
`pip list`
```
apt-xapian-index (0.45)
bd2k-python-lib (1.10.dev6)
boto (2.38.0)
cffi (1.3.1)
chardet (2.0.1)
Cheetah (2.4.4)
cloud-init (0.7.5)
colorama (0.2.5)
configobj (4.7.2)
google-common (0.0.1)
html5lib (0.999)
jsonpatch (1.3)
jsonpointer (1.0)
Landscape-Client (14.12)
mesos (0.25.0)
mesos.interface (0.25.0)
oauth (1.0.1)
PAM (0.4.2)
pip (7.1.2)
prettytable (0.7.2)
protobuf (2.6.1)
psutil (3.0.1)
pycparser (2.14)
pycurl (7.19.3)
PyNaCl (0.3.0)
pyOpenSSL (0.13)
pyserial (2.6)
python-apt (0.9.3.5ubuntu1)
python-debian (0.1.21-nmu2ubuntu2)
PyYAML (3.10)
requests (2.2.1)
s3am (1.0b1.dev30)
setuptools (18.7.1)
six (1.5.2)
ssh-import-id (3.21)
toil (3.1.0b1.dev82)
Twisted-Core (13.2.0)
Twisted-Names (13.2.0)
Twisted-Web (13.2.0)
urllib3 (1.7.1)
virtualenv (13.1.2)
zope.interface (4.0.5)
```

**Comment by jvivian** [comment]
@dyollluap Paul, you've run the pipeline recently without issue correct?

The files are actually [downloaded earlier on](https://github.com/BD2KGenomics/toil-scripts/blob/master/src/toil_scripts/rnaseq_unc/rnaseq_unc_pipeline.py#L296-L300) and should be pulled from filestore at the step you're referencing. 

 I'm puzzled because if it were an issue with the jobstore it would have failed earlier.

**Comment by jvivian** [comment]
@Jeltje  The launch script you linked is for AdTex btw.

**Comment by Jeltje** [comment]
@jvivian I did indeed: [here is the correct one (http://hgwdev.cse.ucsc.edu/~jeltje/toil/launch_unc_mesos.sh)

**Comment by Jeltje** [comment]
Error was due to missing unzip program on toil worker
